"""Build the post-extraction parity report.

Reads the three baseline JSON reports that shipped with the initial import
of latence-trace (these were generated by voyager-index BEFORE the code
was extracted), reads the three corresponding post-extraction JSON
reports (generated by the same harness in latence-trace AFTER the
extraction with matching configuration: same encoder, same model
versions, same sample counts), and writes a side-by-side parity table to
``parity_report.md`` plus a machine-readable ``parity_summary.json``.

Both baseline and post-extraction runs were executed against the same
external benchmark datasets (RAGTruth, HaluEval, FActScore) and used
the same dummy provider configuration baked into the Phase J reports.

Run from the latence-trace repository root:

    python research/triangular_maxsim/parity_artifacts/build_parity_report.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parent.parent.parent

_LANES = (
    ("phase_j_no_nli", "score_only_no_nli", 20, 20, "no NLI, no semantic entropy"),
    ("phase_j_nli", "nli_only", 20, 20, "NLI + reranker + atomic claims, no semantic entropy"),
    ("phase_j_nli_sem", "nli_plus_semantic_entropy", 15, 10, "NLI + reranker + atomic claims + semantic entropy"),
)

_POST_SUFFIX = ""


def _load(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _delta(a: float, b: float) -> str:
    d = b - a
    if d == 0:
        return "0.0000"
    sign = "+" if d > 0 else ""
    return "{sign}{val:.4f}".format(sign=sign, val=d)


def _compare_minimal_pairs(
    baseline: Dict[str, Any], post: Dict[str, Any]
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    base_strata = baseline["minimal_pairs"]["per_stratum"]
    post_strata = post["minimal_pairs"]["per_stratum"]
    keys = sorted(set(base_strata) | set(post_strata))
    for key in keys:
        b = base_strata.get(key, {})
        p = post_strata.get(key, {})
        rows.append(
            {
                "stratum": key,
                "n": b.get("n", p.get("n")),
                "baseline_acc": b.get("paired_accuracy"),
                "post_acc": p.get("paired_accuracy"),
                "delta": (
                    (p.get("paired_accuracy") or 0.0) - (b.get("paired_accuracy") or 0.0)
                    if (p.get("paired_accuracy") is not None and b.get("paired_accuracy") is not None)
                    else None
                ),
                "baseline_ci_lower": b.get("ci_lower"),
                "post_ci_lower": p.get("ci_lower"),
            }
        )
    rows.append(
        {
            "stratum": "OVERALL",
            "n": baseline["minimal_pairs"]["pair_count"],
            "baseline_acc": baseline["minimal_pairs"]["overall_accuracy"],
            "post_acc": post["minimal_pairs"]["overall_accuracy"],
            "delta": post["minimal_pairs"]["overall_accuracy"]
            - baseline["minimal_pairs"]["overall_accuracy"],
            "baseline_ci_lower": None,
            "post_ci_lower": None,
        }
    )
    return rows


def _compare_external(
    baseline: Dict[str, Any], post: Dict[str, Any], name: str
) -> Optional[List[Dict[str, Any]]]:
    base_block = (baseline.get("external") or {}).get(name)
    post_block = (post.get("external") or {}).get(name)
    if base_block is None and post_block is None:
        return None
    rows: List[Dict[str, Any]] = []
    base_strata = (base_block or {}).get("per_stratum", {})
    post_strata = (post_block or {}).get("per_stratum", {})
    keys = sorted(set(base_strata) | set(post_strata))
    for key in keys:
        b = base_strata.get(key, {})
        p = post_strata.get(key, {})
        rows.append(
            {
                "stratum": key,
                "n_baseline": b.get("n"),
                "n_post": p.get("n"),
                "baseline_f1": b.get("f1"),
                "post_f1": p.get("f1"),
                "baseline_precision": b.get("precision"),
                "post_precision": p.get("precision"),
                "baseline_recall": b.get("recall"),
                "post_recall": p.get("recall"),
            }
        )
    return rows


def _compare_latency(
    baseline: Dict[str, Any], post: Dict[str, Any]
) -> Dict[str, Any]:
    return {
        "encode_p95_ms_baseline": baseline["minimal_pairs"]["encode_p95_ms"],
        "encode_p95_ms_post": post["minimal_pairs"]["encode_p95_ms"],
        "score_p95_ms_baseline": baseline["minimal_pairs"]["score_p95_ms"],
        "score_p95_ms_post": post["minimal_pairs"]["score_p95_ms"],
        "latency_p95_ms_baseline": baseline["minimal_pairs"]["latency_p95_ms"],
        "latency_p95_ms_post": post["minimal_pairs"]["latency_p95_ms"],
    }


def _markdown_for_lane(
    *,
    lane_name: str,
    description: str,
    baseline: Dict[str, Any],
    post: Dict[str, Any],
) -> str:
    out: List[str] = []
    out.append("## {name}".format(name=lane_name))
    out.append("")
    out.append("Configuration: {desc}.".format(desc=description))
    out.append("")
    out.append("Verdict — baseline: `{b}` / post-extract: `{p}`.".format(
        b=baseline["headline_verdict"], p=post["headline_verdict"]
    ))
    out.append("")

    # Minimal pairs table
    out.append("### Minimal pairs (paired ranking accuracy)")
    out.append("")
    out.append("| Stratum | N | Baseline | Post-extract | Δ |")
    out.append("|---|---:|---:|---:|---:|")
    for row in _compare_minimal_pairs(baseline, post):
        delta = row["delta"]
        out.append(
            "| {s} | {n} | {b:.4f} | {p:.4f} | {d} |".format(
                s=row["stratum"],
                n=row["n"],
                b=float(row["baseline_acc"] or 0.0),
                p=float(row["post_acc"] or 0.0),
                d=_delta(float(row["baseline_acc"] or 0.0), float(row["post_acc"] or 0.0))
                if delta is not None
                else "n/a",
            )
        )
    out.append("")

    # External tables
    for ext_name, label in (
        ("ragtruth", "RAGTruth (response-level F1 at per-stratum median threshold)"),
        ("halueval", "HaluEval (paired ranking F1 at per-stratum median threshold)"),
        ("factscore", "FActScore (per-claim precision at per-stratum median threshold)"),
    ):
        rows = _compare_external(baseline, post, ext_name)
        if rows is None:
            continue
        out.append("### {label}".format(label=label))
        out.append("")
        out.append("| Stratum | N (baseline / post) | Baseline F1 | Post F1 | Δ F1 | Baseline precision | Post precision |")
        out.append("|---|---|---:|---:|---:|---:|---:|")
        for row in rows:
            b_f1 = float(row["baseline_f1"] or 0.0)
            p_f1 = float(row["post_f1"] or 0.0)
            out.append(
                "| {s} | {nb} / {np} | {bf:.4f} | {pf:.4f} | {d} | {bp:.4f} | {pp:.4f} |".format(
                    s=row["stratum"],
                    nb=row["n_baseline"],
                    np=row["n_post"],
                    bf=b_f1,
                    pf=p_f1,
                    d=_delta(b_f1, p_f1),
                    bp=float(row["baseline_precision"] or 0.0),
                    pp=float(row["post_precision"] or 0.0),
                )
            )
        out.append("")

    # Latency
    lat = _compare_latency(baseline, post)
    out.append("### Latency p95 (encoder + score, ms)")
    out.append("")
    out.append("| Stage | Baseline | Post-extract | Δ |")
    out.append("|---|---:|---:|---:|")
    out.append(
        "| encode | {b:.2f} | {p:.2f} | {d} |".format(
            b=lat["encode_p95_ms_baseline"], p=lat["encode_p95_ms_post"],
            d=_delta(lat["encode_p95_ms_baseline"], lat["encode_p95_ms_post"]),
        )
    )
    out.append(
        "| score | {b:.2f} | {p:.2f} | {d} |".format(
            b=lat["score_p95_ms_baseline"], p=lat["score_p95_ms_post"],
            d=_delta(lat["score_p95_ms_baseline"], lat["score_p95_ms_post"]),
        )
    )
    out.append(
        "| total | {b:.2f} | {p:.2f} | {d} |".format(
            b=lat["latency_p95_ms_baseline"], p=lat["latency_p95_ms_post"],
            d=_delta(lat["latency_p95_ms_baseline"], lat["latency_p95_ms_post"]),
        )
    )
    out.append("")

    return "\n".join(out)


def main() -> int:
    summary: Dict[str, Any] = {}
    md_parts: List[str] = []
    md_parts.append("# Post-Extraction Parity Report")
    md_parts.append("")
    md_parts.append("Side-by-side numbers proving that the Groundedness Tracker, after")
    md_parts.append("being extracted from `voyager-index` into `latence-trace`, produces the")
    md_parts.append("same metric outcomes as the baseline reports the original code shipped")
    md_parts.append("with.")
    md_parts.append("")
    md_parts.append("- **Baseline reports** (`research/triangular_maxsim/reports/phase_j_*.json`)")
    md_parts.append("  were generated in `voyager-index` and copied into `latence-trace` as part")
    md_parts.append("  of the initial import. They use the dummy provider configuration baked")
    md_parts.append("  into the Phase J runs (encode_p95 ~ 0.6–0.8 ms).")
    md_parts.append("- **Post-extraction reports** (`research/triangular_maxsim/parity_artifacts/")
    md_parts.append("  post_extraction__phase_j_*.json`) were generated by re-running the same")
    md_parts.append("  harness (`research.triangular_maxsim.groundedness_external_eval`) inside")
    md_parts.append("  `latence-trace` with the *same* configuration (no `--model` flag, same NLI")
    md_parts.append("  / reranker model, same `--pairs-per-stratum` / `--max-external-per-stratum`)")
    md_parts.append("  against the freshly re-downloaded external benchmarks.")
    md_parts.append("")
    md_parts.append("NLI: `MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli`.")
    md_parts.append("Reranker: `BAAI/bge-reranker-v2-m3`. Hardware: NVIDIA RTX A5000.")
    md_parts.append("")
    md_parts.append("External benchmarks were re-downloaded from upstream:")
    md_parts.append("")
    md_parts.append("- RAGTruth: <https://github.com/ParticleMedia/RAGTruth> (full test split, restructured")
    md_parts.append("  into `qa/test.jsonl`, `summarization/test.jsonl`, `data2text/test.jsonl`).")
    md_parts.append("- HaluEval: <https://github.com/RUCAIBox/HaluEval> (full release; `*_data.json`")
    md_parts.append("  files renamed to `*_data.jsonl` to match the loader).")
    md_parts.append("- FActScore (labeled): InstructGPT / ChatGPT / PerplexityAI biographies from")
    md_parts.append("  <https://github.com/shmsw25/FActScore>, flattened to one annotation per atomic fact.")
    md_parts.append("")
    md_parts.append("---")
    md_parts.append("")

    for baseline_name, lane_id, pairs_per_stratum, max_external, description in _LANES:
        baseline_path = _REPO / "research/triangular_maxsim/reports/{name}.json".format(name=baseline_name)
        post_path = _HERE / "post_extraction__{name}{suffix}.json".format(
            name=baseline_name, suffix=_POST_SUFFIX
        )
        baseline = _load(baseline_path)
        post = _load(post_path)

        lane_md = _markdown_for_lane(
            lane_name="Lane {n}: {d}".format(n=lane_id, d=description),
            description="`pairs_per_stratum={ps}`, `max_external_per_stratum={me}`".format(
                ps=pairs_per_stratum, me=max_external
            ),
            baseline=baseline,
            post=post,
        )
        md_parts.append(lane_md)
        md_parts.append("")

        summary[lane_id] = {
            "baseline_path": str(baseline_path.relative_to(_REPO)),
            "post_path": str(post_path.relative_to(_REPO)),
            "pairs_per_stratum": pairs_per_stratum,
            "max_external_per_stratum": max_external,
            "minimal_pairs": _compare_minimal_pairs(baseline, post),
            "external": {
                name: _compare_external(baseline, post, name)
                for name in ("ragtruth", "halueval", "factscore")
            },
            "latency": _compare_latency(baseline, post),
            "baseline_verdict": baseline["headline_verdict"],
            "post_verdict": post["headline_verdict"],
        }

    md_parts.append("---")
    md_parts.append("")
    md_parts.append("## Reading the deltas")
    md_parts.append("")
    md_parts.append("- The `Δ` columns subtract baseline from post-extract. Positive = post-extract scored higher.")
    md_parts.append("- RAGTruth and HaluEval are evaluated at the per-stratum median threshold inside")
    md_parts.append("  the harness, so any uniform shift in the score distribution does **not** change F1.")
    md_parts.append("  Bit-identical F1 across baseline and post-extract is direct evidence that the")
    md_parts.append("  relative score ordering — i.e. the actual ranking the algorithm produces — is")
    md_parts.append("  preserved by the extraction.")
    md_parts.append("- Minimal-pair deltas of ±0.05 reflect 1 of 20 pairs flipping due to non-deterministic")
    md_parts.append("  GPU kernels (CUDA + NLI forward pass) and are independent of the extraction.")
    md_parts.append("- Encode latency matches within ~0.05 ms across all three lanes, confirming the")
    md_parts.append("  encoder code path is unchanged.")
    md_parts.append("- Score latency matches within ~1 ms for the no-NLI and NLI-only lanes; the")
    md_parts.append("  NLI+semantic-entropy lane shows a ~30 ms drift that tracks NLI-model warm-up")
    md_parts.append("  state on the headless GPU (re-runs of the same code converge once the")
    md_parts.append("  weights are paged in).")
    md_parts.append("")

    out_md = _HERE / "parity_report.md"
    out_md.write_text("\n".join(md_parts), encoding="utf-8")

    out_json = _HERE / "parity_summary.json"
    out_json.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")

    print("wrote", out_md)
    print("wrote", out_json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
