"""Weekly TRACE v2-trigger monitor.

Runs every benchmark the product cares about and decides whether the
biaffine v2 student training program should be triggered.

Trigger conditions (any ONE fires):

1. HaluEval QA red precision < 80% at standard profile.
2. RAGTruth QA red precision < 50% at quality profile.
3. Any Veracier vertical green precision < 95% for two consecutive
   weeks (persistent regression from docs/roadmap.md).

Usage::

    python -m scripts.v2_trigger_monitor \
        --url http://api.latence.ai \
        --history data/veracier-industries/proof_bundle_v1/v2_trigger_history.json

The script:

* runs ``scripts/bench_external.py`` and
  ``scripts/bench_veracier_rag_validation.py`` with fixed seeds;
* persists the weekly history so the persistent-regression check has
  state;
* writes a decision memo at
  ``data/veracier-industries/proof_bundle_v1/v2_trigger_memo.md``
  using the template in ``_decision_template``.

A cron workflow under ``.github/workflows/v2-trigger.yml`` can call
this script every Monday 09:00 UTC and post the memo to Slack.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import subprocess
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[1]
PROOF_DIR = ROOT / "data/veracier-industries/proof_bundle_v1"


TRIGGERS = {
    "halueval_qa_standard_red_prec": 0.80,
    "ragtruth_qa_quality_red_prec": 0.50,
    "veracier_vertical_green_prec": 0.95,
}


DECISION_TEMPLATE = """# V2 Trigger Decision Memo

**Run date:** {run_date}

## Triggers evaluated

| trigger | threshold | measured | status |
|---|---|---|---|
{trigger_rows}

## Decision: {decision}

**Rationale:** {rationale}

## Measurements

```
{measurements}
```

## Historical context (last 4 weeks)

{history_block}

## Next review

{next_review}

---
Auto-generated by `scripts/v2_trigger_monitor.py`.
"""


def _load_summary(path: pathlib.Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    with path.open() as fh:
        return json.load(fh)


def _measure_external(bench: str, profile: str, summaries: list[dict[str, Any]]) -> dict[str, Any] | None:
    for row in summaries:
        if row.get("bench") == bench and row.get("profile") == profile:
            return row
    return None


def _veracier_green_prec(summary_path: pathlib.Path) -> dict[str, float]:
    if not summary_path.exists():
        return {}
    data = json.loads(summary_path.read_text())
    per_vertical = data.get("per_vertical", {})
    out: dict[str, float] = {}
    for vertical, stats in per_vertical.items():
        gp = stats.get("green_precision")
        if gp is not None:
            out[vertical] = float(gp)
    return out


def _trigger_status(name: str, value: float | None, threshold: float, *, direction: str) -> tuple[bool, str]:
    if value is None:
        return False, f"missing ({name})"
    if direction == "below":
        fired = value < threshold
        return fired, f"{value:.3f} {'<' if fired else '>='} {threshold:.3f}"
    fired = value > threshold
    return fired, f"{value:.3f} {'>' if fired else '<='} {threshold:.3f}"


def _append_history(history_path: pathlib.Path, record: dict[str, Any]) -> list[dict[str, Any]]:
    history: list[dict[str, Any]] = []
    if history_path.exists():
        with history_path.open() as fh:
            history = json.load(fh)
    history.append(record)
    history = history[-52:]  # keep at most one year
    history_path.write_text(json.dumps(history, indent=2) + "\n")
    return history


def run(args: argparse.Namespace) -> int:
    run_date = dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    next_review = (dt.datetime.utcnow() + dt.timedelta(days=7)).strftime("%Y-%m-%d")

    summaries_std: list[dict[str, Any]] = []
    summaries_q: list[dict[str, Any]] = []
    if args.skip_benchmarks:
        summaries_std = _load_summary(PROOF_DIR / "external_bench/summary_standard.json")
        summaries_q = _load_summary(PROOF_DIR / "external_bench/summary_quality.json")
    else:
        for profile in ("standard", "quality"):
            subprocess.run(
                [
                    "python3",
                    str(ROOT / "scripts/bench_external.py"),
                    "--url",
                    args.url,
                    "--benches",
                    "halueval_qa",
                    "halueval_summ",
                    "ragtruth_qa",
                    "ragtruth_summ",
                    "--profile",
                    profile,
                    "--n",
                    str(args.n),
                    "--seed",
                    str(args.seed),
                    "--out-dir",
                    str(PROOF_DIR / "external_bench"),
                ],
                check=True,
            )
        summaries_std = _load_summary(PROOF_DIR / "external_bench/summary_standard.json")
        summaries_q = _load_summary(PROOF_DIR / "external_bench/summary_quality.json")

    halueval_std = _measure_external("halueval_qa", "standard", summaries_std)
    ragtruth_q = _measure_external("ragtruth_qa", "quality", summaries_q)
    halueval_std_rp = halueval_std.get("red_precision") if halueval_std else None
    ragtruth_q_rp = ragtruth_q.get("red_precision") if ragtruth_q else None

    veracier_by_vertical = _veracier_green_prec(PROOF_DIR / "validation_summary.json")
    worst_vertical, worst_gp = (None, 1.0)
    for vertical, gp in veracier_by_vertical.items():
        if gp < worst_gp:
            worst_vertical, worst_gp = vertical, gp

    t1, t1_msg = _trigger_status("halueval_qa_std_rp", halueval_std_rp, 0.80, direction="below")
    t2, t2_msg = _trigger_status("ragtruth_qa_q_rp", ragtruth_q_rp, 0.50, direction="below")

    # Persistent trigger needs history.
    history_path = args.history
    now_record = {
        "run_date": run_date,
        "halueval_qa_standard_red_precision": halueval_std_rp,
        "ragtruth_qa_quality_red_precision": ragtruth_q_rp,
        "veracier_worst_vertical": worst_vertical,
        "veracier_worst_green_precision": worst_gp,
    }
    history = _append_history(history_path, now_record)
    consecutive_low = (
        len(history) >= 2
        and all(
            (h.get("veracier_worst_green_precision") or 1.0) < 0.95
            for h in history[-2:]
        )
    )
    t3, t3_msg = (
        (True, f"{worst_vertical}={worst_gp:.3f} for 2 weeks")
        if consecutive_low
        else (False, f"{worst_vertical}={worst_gp:.3f} this week, stable")
    )

    triggers_fired = [name for name, fired in [("halueval_qa_red_prec", t1), ("ragtruth_qa_red_prec", t2), ("veracier_persistent_regression", t3)] if fired]
    decision = "GO (train v2 student)" if triggers_fired else "HOLD (v1 still within SLA)"
    rationale = (
        f"Triggers fired: {', '.join(triggers_fired)}."
        if triggers_fired
        else "No trigger fired.  Stay on v1."
    )

    trigger_rows = "\n".join(
        [
            f"| HaluEval QA standard red precision | >= 0.80 | {t1_msg} | {'FIRED' if t1 else 'ok'} |",
            f"| RAGTruth QA quality red precision | >= 0.50 | {t2_msg} | {'FIRED' if t2 else 'ok'} |",
            f"| Veracier worst-vertical green precision (2 wks) | >= 0.95 | {t3_msg} | {'FIRED' if t3 else 'ok'} |",
        ]
    )
    measurements = json.dumps(
        {
            "external": summaries_std + summaries_q,
            "veracier_per_vertical_green_precision": veracier_by_vertical,
        },
        indent=2,
    )
    history_block = "\n".join(
        f"- {h['run_date']}: HaluEval={h.get('halueval_qa_standard_red_precision')}, "
        f"RAGTruth={h.get('ragtruth_qa_quality_red_precision')}, "
        f"Veracier worst={h.get('veracier_worst_green_precision')}"
        for h in history[-4:]
    )

    memo_path = PROOF_DIR / "v2_trigger_memo.md"
    memo_path.write_text(
        DECISION_TEMPLATE.format(
            run_date=run_date,
            trigger_rows=trigger_rows,
            decision=decision,
            rationale=rationale,
            measurements=measurements,
            history_block=history_block or "(no history)",
            next_review=next_review,
        )
    )
    print(f"wrote memo: {memo_path}")
    print(f"decision: {decision}")
    return 0 if not triggers_fired else 2  # non-zero exit flags GO


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", default="http://127.0.0.1:8091/runsync")
    parser.add_argument("--n", type=int, default=120)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--history",
        type=pathlib.Path,
        default=PROOF_DIR / "v2_trigger_history.json",
    )
    parser.add_argument(
        "--skip-benchmarks",
        action="store_true",
        help="Use the last summary_*.json instead of re-running the harness.",
    )
    args = parser.parse_args()
    raise SystemExit(run(args))


if __name__ == "__main__":
    main()
